-- =====================================================================
-- SILVER · 04_games.sql
-- FOOTBALL.RAW.GAMES -> FOOTBALL.SILVER.GAMES
--
-- AVISO (inferido, no verificado con datos reales): comprueba antes con
--   SELECT * FROM FOOTBALL.RAW.GAMES LIMIT 5;
-- AGGREGATE se deja como STRING a propósito: en partidos de eliminatoria
-- a doble partido puede venir como marcador textual (p.ej. "3:2"), no
-- como número.
-- =====================================================================

CREATE TABLE IF NOT EXISTS FOOTBALL.SILVER.GAMES (
  GAME_ID                  NUMBER        NOT NULL,
  COMPETITION_ID            STRING,
  SEASON                    NUMBER,
  ROUND                     STRING,
  GAME_DATE                 DATE,
  HOME_CLUB_ID              NUMBER,
  AWAY_CLUB_ID              NUMBER,
  HOME_CLUB_GOALS           NUMBER,
  AWAY_CLUB_GOALS           NUMBER,
  HOME_CLUB_POSITION        NUMBER,
  AWAY_CLUB_POSITION        NUMBER,
  HOME_CLUB_MANAGER_NAME    STRING,
  AWAY_CLUB_MANAGER_NAME    STRING,
  STADIUM                   STRING,
  ATTENDANCE                NUMBER,
  REFEREE                   STRING,
  URL                       STRING,
  HOME_CLUB_FORMATION       STRING,
  AWAY_CLUB_FORMATION       STRING,
  HOME_CLUB_NAME            STRING,
  AWAY_CLUB_NAME            STRING,
  AGGREGATE                 STRING,
  COMPETITION_TYPE          STRING,
  _SOURCE_FILE              STRING,
  _RAW_LOADED_AT            TIMESTAMP_NTZ,
  _SILVER_LOADED_AT         TIMESTAMP_NTZ,
  PRIMARY KEY (GAME_ID)
);

CREATE STREAM IF NOT EXISTS FOOTBALL.SILVER.STREAM_RAW_GAMES
  ON TABLE FOOTBALL.RAW.GAMES
  APPEND_ONLY = TRUE;

-- Nota: la columna original del CSV se llama DATE. La renombramos a
-- GAME_DATE en SILVER porque DATE es también el nombre de un tipo de
-- dato en Snowflake, y aunque suele funcionar igualmente como
-- identificador, es más legible y menos propenso a errores evitarlo.
CREATE OR REPLACE TASK FOOTBALL.SILVER.TASK_LOAD_GAMES
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 30 8 * * 6 Europe/Madrid'
WHEN
  SYSTEM$STREAM_HAS_DATA('FOOTBALL.SILVER.STREAM_RAW_GAMES')
AS
MERGE INTO FOOTBALL.SILVER.GAMES AS tgt
USING (
  SELECT
    TRY_TO_NUMBER(GAME_ID)                  AS GAME_ID,
    NULLIF(TRIM(COMPETITION_ID), '')        AS COMPETITION_ID,
    TRY_TO_NUMBER(SEASON)                   AS SEASON,
    NULLIF(TRIM(ROUND), '')                 AS ROUND,
    TRY_TO_DATE(DATE)                       AS GAME_DATE,
    TRY_TO_NUMBER(HOME_CLUB_ID)             AS HOME_CLUB_ID,
    TRY_TO_NUMBER(AWAY_CLUB_ID)             AS AWAY_CLUB_ID,
    TRY_TO_NUMBER(HOME_CLUB_GOALS)          AS HOME_CLUB_GOALS,
    TRY_TO_NUMBER(AWAY_CLUB_GOALS)          AS AWAY_CLUB_GOALS,
    TRY_TO_NUMBER(HOME_CLUB_POSITION)       AS HOME_CLUB_POSITION,
    TRY_TO_NUMBER(AWAY_CLUB_POSITION)       AS AWAY_CLUB_POSITION,
    NULLIF(TRIM(HOME_CLUB_MANAGER_NAME), '') AS HOME_CLUB_MANAGER_NAME,
    NULLIF(TRIM(AWAY_CLUB_MANAGER_NAME), '') AS AWAY_CLUB_MANAGER_NAME,
    NULLIF(TRIM(STADIUM), '')               AS STADIUM,
    TRY_TO_NUMBER(ATTENDANCE)               AS ATTENDANCE,
    NULLIF(TRIM(REFEREE), '')               AS REFEREE,
    NULLIF(TRIM(URL), '')                   AS URL,
    NULLIF(TRIM(HOME_CLUB_FORMATION), '')   AS HOME_CLUB_FORMATION,
    NULLIF(TRIM(AWAY_CLUB_FORMATION), '')   AS AWAY_CLUB_FORMATION,
    NULLIF(TRIM(HOME_CLUB_NAME), '')        AS HOME_CLUB_NAME,
    NULLIF(TRIM(AWAY_CLUB_NAME), '')        AS AWAY_CLUB_NAME,
    NULLIF(TRIM(AGGREGATE), '')             AS AGGREGATE,
    NULLIF(TRIM(COMPETITION_TYPE), '')      AS COMPETITION_TYPE,
    _SOURCE_FILE                            AS _SOURCE_FILE,
    _LOADED_AT                              AS _RAW_LOADED_AT
  FROM FOOTBALL.SILVER.STREAM_RAW_GAMES
  WHERE GAME_ID IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY GAME_ID
    ORDER BY _LOADED_AT DESC
  ) = 1
) AS src
ON tgt.GAME_ID = src.GAME_ID
WHEN MATCHED THEN UPDATE SET
  tgt.COMPETITION_ID         = src.COMPETITION_ID,
  tgt.SEASON                 = src.SEASON,
  tgt.ROUND                  = src.ROUND,
  tgt.GAME_DATE              = src.GAME_DATE,
  tgt.HOME_CLUB_ID           = src.HOME_CLUB_ID,
  tgt.AWAY_CLUB_ID           = src.AWAY_CLUB_ID,
  tgt.HOME_CLUB_GOALS        = src.HOME_CLUB_GOALS,
  tgt.AWAY_CLUB_GOALS        = src.AWAY_CLUB_GOALS,
  tgt.HOME_CLUB_POSITION     = src.HOME_CLUB_POSITION,
  tgt.AWAY_CLUB_POSITION     = src.AWAY_CLUB_POSITION,
  tgt.HOME_CLUB_MANAGER_NAME = src.HOME_CLUB_MANAGER_NAME,
  tgt.AWAY_CLUB_MANAGER_NAME = src.AWAY_CLUB_MANAGER_NAME,
  tgt.STADIUM                = src.STADIUM,
  tgt.ATTENDANCE             = src.ATTENDANCE,
  tgt.REFEREE                = src.REFEREE,
  tgt.URL                    = src.URL,
  tgt.HOME_CLUB_FORMATION    = src.HOME_CLUB_FORMATION,
  tgt.AWAY_CLUB_FORMATION    = src.AWAY_CLUB_FORMATION,
  tgt.HOME_CLUB_NAME         = src.HOME_CLUB_NAME,
  tgt.AWAY_CLUB_NAME         = src.AWAY_CLUB_NAME,
  tgt.AGGREGATE              = src.AGGREGATE,
  tgt.COMPETITION_TYPE       = src.COMPETITION_TYPE,
  tgt._SOURCE_FILE           = src._SOURCE_FILE,
  tgt._RAW_LOADED_AT         = src._RAW_LOADED_AT,
  tgt._SILVER_LOADED_AT      = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  GAME_ID, COMPETITION_ID, SEASON, ROUND, GAME_DATE, HOME_CLUB_ID,
  AWAY_CLUB_ID, HOME_CLUB_GOALS, AWAY_CLUB_GOALS, HOME_CLUB_POSITION,
  AWAY_CLUB_POSITION, HOME_CLUB_MANAGER_NAME, AWAY_CLUB_MANAGER_NAME,
  STADIUM, ATTENDANCE, REFEREE, URL, HOME_CLUB_FORMATION,
  AWAY_CLUB_FORMATION, HOME_CLUB_NAME, AWAY_CLUB_NAME, AGGREGATE,
  COMPETITION_TYPE, _SOURCE_FILE, _RAW_LOADED_AT, _SILVER_LOADED_AT
) VALUES (
  src.GAME_ID, src.COMPETITION_ID, src.SEASON, src.ROUND, src.GAME_DATE,
  src.HOME_CLUB_ID, src.AWAY_CLUB_ID, src.HOME_CLUB_GOALS,
  src.AWAY_CLUB_GOALS, src.HOME_CLUB_POSITION, src.AWAY_CLUB_POSITION,
  src.HOME_CLUB_MANAGER_NAME, src.AWAY_CLUB_MANAGER_NAME, src.STADIUM,
  src.ATTENDANCE, src.REFEREE, src.URL, src.HOME_CLUB_FORMATION,
  src.AWAY_CLUB_FORMATION, src.HOME_CLUB_NAME, src.AWAY_CLUB_NAME,
  src.AGGREGATE, src.COMPETITION_TYPE, src._SOURCE_FILE,
  src._RAW_LOADED_AT, CURRENT_TIMESTAMP()
);

ALTER TASK FOOTBALL.SILVER.TASK_LOAD_GAMES RESUME;

-- Validación:
-- SELECT * FROM FOOTBALL.SILVER.GAMES;
-- EXECUTE TASK FOOTBALL.SILVER.TASK_LOAD_GAMES;
