-- =====================================================================
-- SILVER · 05_club_games.sql
-- FOOTBALL.RAW.CLUB_GAMES -> FOOTBALL.SILVER.CLUB_GAMES
--
-- AVISO (inferido, no verificado con datos reales): comprueba antes con
--   SELECT * FROM FOOTBALL.RAW.CLUB_GAMES LIMIT 5;
-- Esta tabla no tiene una columna de id propio: cada partido genera dos
-- filas (una por club), así que la clave de negocio es la pareja
-- (GAME_ID, CLUB_ID). IS_WIN se trata como NUMBER asumiendo que viene
-- como 0/1; si en tus datos viene como texto ("True"/"False"), cambia
-- TRY_TO_NUMBER por TRY_TO_BOOLEAN y el tipo de columna por BOOLEAN.
-- =====================================================================

CREATE TABLE IF NOT EXISTS FOOTBALL.SILVER.CLUB_GAMES (
  GAME_ID                NUMBER    NOT NULL,
  CLUB_ID                NUMBER    NOT NULL,
  OWN_GOALS              NUMBER,
  OWN_POSITION           NUMBER,
  OWN_MANAGER_NAME       STRING,
  OPPONENT_ID            NUMBER,
  OPPONENT_GOALS         NUMBER,
  OPPONENT_POSITION      NUMBER,
  OPPONENT_MANAGER_NAME  STRING,
  HOSTING                STRING,
  IS_WIN                 NUMBER,
  _SOURCE_FILE           STRING,
  _RAW_LOADED_AT         TIMESTAMP_NTZ,
  _SILVER_LOADED_AT      TIMESTAMP_NTZ,
  PRIMARY KEY (GAME_ID, CLUB_ID)
);

CREATE STREAM IF NOT EXISTS FOOTBALL.SILVER.STREAM_RAW_CLUB_GAMES
  ON TABLE FOOTBALL.RAW.CLUB_GAMES
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK FOOTBALL.SILVER.TASK_LOAD_CLUB_GAMES
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 30 8 * * 6 Europe/Madrid'
WHEN
  SYSTEM$STREAM_HAS_DATA('FOOTBALL.SILVER.STREAM_RAW_CLUB_GAMES')
AS
MERGE INTO FOOTBALL.SILVER.CLUB_GAMES AS tgt
USING (
  SELECT
    TRY_TO_NUMBER(GAME_ID)                    AS GAME_ID,
    TRY_TO_NUMBER(CLUB_ID)                    AS CLUB_ID,
    TRY_TO_NUMBER(OWN_GOALS)                  AS OWN_GOALS,
    TRY_TO_NUMBER(OWN_POSITION)               AS OWN_POSITION,
    NULLIF(TRIM(OWN_MANAGER_NAME), '')        AS OWN_MANAGER_NAME,
    TRY_TO_NUMBER(OPPONENT_ID)                AS OPPONENT_ID,
    TRY_TO_NUMBER(OPPONENT_GOALS)             AS OPPONENT_GOALS,
    TRY_TO_NUMBER(OPPONENT_POSITION)          AS OPPONENT_POSITION,
    NULLIF(TRIM(OPPONENT_MANAGER_NAME), '')   AS OPPONENT_MANAGER_NAME,
    NULLIF(TRIM(HOSTING), '')                 AS HOSTING,
    TRY_TO_NUMBER(IS_WIN)                     AS IS_WIN,
    _SOURCE_FILE                              AS _SOURCE_FILE,
    _LOADED_AT                                AS _RAW_LOADED_AT
  FROM FOOTBALL.SILVER.STREAM_RAW_CLUB_GAMES
  WHERE GAME_ID IS NOT NULL AND CLUB_ID IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY GAME_ID, CLUB_ID
    ORDER BY _LOADED_AT DESC
  ) = 1
) AS src
ON tgt.GAME_ID = src.GAME_ID AND tgt.CLUB_ID = src.CLUB_ID
WHEN MATCHED THEN UPDATE SET
  tgt.OWN_GOALS             = src.OWN_GOALS,
  tgt.OWN_POSITION          = src.OWN_POSITION,
  tgt.OWN_MANAGER_NAME      = src.OWN_MANAGER_NAME,
  tgt.OPPONENT_ID           = src.OPPONENT_ID,
  tgt.OPPONENT_GOALS        = src.OPPONENT_GOALS,
  tgt.OPPONENT_POSITION     = src.OPPONENT_POSITION,
  tgt.OPPONENT_MANAGER_NAME = src.OPPONENT_MANAGER_NAME,
  tgt.HOSTING               = src.HOSTING,
  tgt.IS_WIN                = src.IS_WIN,
  tgt._SOURCE_FILE          = src._SOURCE_FILE,
  tgt._RAW_LOADED_AT        = src._RAW_LOADED_AT,
  tgt._SILVER_LOADED_AT     = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  GAME_ID, CLUB_ID, OWN_GOALS, OWN_POSITION, OWN_MANAGER_NAME,
  OPPONENT_ID, OPPONENT_GOALS, OPPONENT_POSITION, OPPONENT_MANAGER_NAME,
  HOSTING, IS_WIN, _SOURCE_FILE, _RAW_LOADED_AT, _SILVER_LOADED_AT
) VALUES (
  src.GAME_ID, src.CLUB_ID, src.OWN_GOALS, src.OWN_POSITION,
  src.OWN_MANAGER_NAME, src.OPPONENT_ID, src.OPPONENT_GOALS,
  src.OPPONENT_POSITION, src.OPPONENT_MANAGER_NAME, src.HOSTING,
  src.IS_WIN, src._SOURCE_FILE, src._RAW_LOADED_AT, CURRENT_TIMESTAMP()
);

ALTER TASK FOOTBALL.SILVER.TASK_LOAD_CLUB_GAMES RESUME;

-- Validación:
-- SELECT * FROM FOOTBALL.SILVER.CLUB_GAMES;
-- EXECUTE TASK FOOTBALL.SILVER.TASK_LOAD_CLUB_GAMES;
