-- =====================================================================
-- SILVER · 06_appearances.sql
-- FOOTBALL.RAW.APPEARANCES -> FOOTBALL.SILVER.APPEARANCES
--
-- AVISO (inferido, no verificado con datos reales): comprueba antes con
--   SELECT * FROM FOOTBALL.RAW.APPEARANCES LIMIT 5;
-- APPEARANCE_ID ya viene como una clave única de negocio propia (según
-- el dataset público, algo como "game_id_player_id"), así que se usa
-- directamente como PRIMARY KEY, sin necesidad de clave compuesta.
-- =====================================================================

CREATE TABLE IF NOT EXISTS FOOTBALL.SILVER.APPEARANCES (
  APPEARANCE_ID           STRING    NOT NULL,
  GAME_ID                 NUMBER,
  PLAYER_ID               NUMBER,
  PLAYER_CLUB_ID          NUMBER,
  PLAYER_CURRENT_CLUB_ID  NUMBER,
  APPEARANCE_DATE         DATE,
  PLAYER_NAME             STRING,
  COMPETITION_ID          STRING,
  YELLOW_CARDS            NUMBER,
  RED_CARDS               NUMBER,
  GOALS                   NUMBER,
  ASSISTS                 NUMBER,
  MINUTES_PLAYED          NUMBER,
  _SOURCE_FILE            STRING,
  _RAW_LOADED_AT          TIMESTAMP_NTZ,
  _SILVER_LOADED_AT       TIMESTAMP_NTZ,
  PRIMARY KEY (APPEARANCE_ID)
);

CREATE STREAM IF NOT EXISTS FOOTBALL.SILVER.STREAM_RAW_APPEARANCES
  ON TABLE FOOTBALL.RAW.APPEARANCES
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK FOOTBALL.SILVER.TASK_LOAD_APPEARANCES
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 30 8 * * 6 Europe/Madrid'
WHEN
  SYSTEM$STREAM_HAS_DATA('FOOTBALL.SILVER.STREAM_RAW_APPEARANCES')
AS
MERGE INTO FOOTBALL.SILVER.APPEARANCES AS tgt
USING (
  SELECT
    NULLIF(TRIM(APPEARANCE_ID), '')      AS APPEARANCE_ID,
    TRY_TO_NUMBER(GAME_ID)               AS GAME_ID,
    TRY_TO_NUMBER(PLAYER_ID)             AS PLAYER_ID,
    TRY_TO_NUMBER(PLAYER_CLUB_ID)        AS PLAYER_CLUB_ID,
    TRY_TO_NUMBER(PLAYER_CURRENT_CLUB_ID) AS PLAYER_CURRENT_CLUB_ID,
    TRY_TO_DATE(DATE)                    AS APPEARANCE_DATE,
    NULLIF(TRIM(PLAYER_NAME), '')        AS PLAYER_NAME,
    NULLIF(TRIM(COMPETITION_ID), '')     AS COMPETITION_ID,
    TRY_TO_NUMBER(YELLOW_CARDS)          AS YELLOW_CARDS,
    TRY_TO_NUMBER(RED_CARDS)             AS RED_CARDS,
    TRY_TO_NUMBER(GOALS)                 AS GOALS,
    TRY_TO_NUMBER(ASSISTS)               AS ASSISTS,
    TRY_TO_NUMBER(MINUTES_PLAYED)        AS MINUTES_PLAYED,
    _SOURCE_FILE                         AS _SOURCE_FILE,
    _LOADED_AT                           AS _RAW_LOADED_AT
  FROM FOOTBALL.SILVER.STREAM_RAW_APPEARANCES
  WHERE APPEARANCE_ID IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY APPEARANCE_ID
    ORDER BY _LOADED_AT DESC
  ) = 1
) AS src
ON tgt.APPEARANCE_ID = src.APPEARANCE_ID
WHEN MATCHED THEN UPDATE SET
  tgt.GAME_ID                = src.GAME_ID,
  tgt.PLAYER_ID               = src.PLAYER_ID,
  tgt.PLAYER_CLUB_ID          = src.PLAYER_CLUB_ID,
  tgt.PLAYER_CURRENT_CLUB_ID  = src.PLAYER_CURRENT_CLUB_ID,
  tgt.APPEARANCE_DATE         = src.APPEARANCE_DATE,
  tgt.PLAYER_NAME             = src.PLAYER_NAME,
  tgt.COMPETITION_ID          = src.COMPETITION_ID,
  tgt.YELLOW_CARDS            = src.YELLOW_CARDS,
  tgt.RED_CARDS               = src.RED_CARDS,
  tgt.GOALS                   = src.GOALS,
  tgt.ASSISTS                 = src.ASSISTS,
  tgt.MINUTES_PLAYED          = src.MINUTES_PLAYED,
  tgt._SOURCE_FILE            = src._SOURCE_FILE,
  tgt._RAW_LOADED_AT          = src._RAW_LOADED_AT,
  tgt._SILVER_LOADED_AT       = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  APPEARANCE_ID, GAME_ID, PLAYER_ID, PLAYER_CLUB_ID,
  PLAYER_CURRENT_CLUB_ID, APPEARANCE_DATE, PLAYER_NAME, COMPETITION_ID,
  YELLOW_CARDS, RED_CARDS, GOALS, ASSISTS, MINUTES_PLAYED,
  _SOURCE_FILE, _RAW_LOADED_AT, _SILVER_LOADED_AT
) VALUES (
  src.APPEARANCE_ID, src.GAME_ID, src.PLAYER_ID, src.PLAYER_CLUB_ID,
  src.PLAYER_CURRENT_CLUB_ID, src.APPEARANCE_DATE, src.PLAYER_NAME,
  src.COMPETITION_ID, src.YELLOW_CARDS, src.RED_CARDS, src.GOALS,
  src.ASSISTS, src.MINUTES_PLAYED, src._SOURCE_FILE, src._RAW_LOADED_AT,
  CURRENT_TIMESTAMP()
);

ALTER TASK FOOTBALL.SILVER.TASK_LOAD_APPEARANCES RESUME;

-- Validación:
-- SELECT * FROM FOOTBALL.SILVER.APPEARANCES;
-- EXECUTE TASK FOOTBALL.SILVER.TASK_LOAD_APPEARANCES;
