-- =====================================================================
-- SILVER · 07_player_valuations.sql
-- FOOTBALL.RAW.PLAYER_VALUATIONS -> FOOTBALL.SILVER.PLAYER_VALUATIONS
--
-- AVISO (inferido, no verificado con datos reales): comprueba antes con
--   SELECT * FROM FOOTBALL.RAW.PLAYER_VALUATIONS LIMIT 5;
-- No hay una columna de id propio: un jugador tiene una valoración por
-- fecha, así que la clave de negocio es la pareja (PLAYER_ID, DATE).
-- =====================================================================

CREATE TABLE IF NOT EXISTS FOOTBALL.SILVER.PLAYER_VALUATIONS (
  PLAYER_ID                              NUMBER    NOT NULL,
  VALUATION_DATE                         DATE      NOT NULL,
  MARKET_VALUE_IN_EUR                    NUMBER,
  CURRENT_CLUB_ID                        NUMBER,
  PLAYER_CLUB_DOMESTIC_COMPETITION_ID    STRING,
  _SOURCE_FILE                           STRING,
  _RAW_LOADED_AT                         TIMESTAMP_NTZ,
  _SILVER_LOADED_AT                      TIMESTAMP_NTZ,
  PRIMARY KEY (PLAYER_ID, VALUATION_DATE)
);

CREATE STREAM IF NOT EXISTS FOOTBALL.SILVER.STREAM_RAW_PLAYER_VALUATIONS
  ON TABLE FOOTBALL.RAW.PLAYER_VALUATIONS
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK FOOTBALL.SILVER.TASK_LOAD_PLAYER_VALUATIONS
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 30 8 * * 6 Europe/Madrid'
WHEN
  SYSTEM$STREAM_HAS_DATA('FOOTBALL.SILVER.STREAM_RAW_PLAYER_VALUATIONS')
AS
MERGE INTO FOOTBALL.SILVER.PLAYER_VALUATIONS AS tgt
USING (
  SELECT
    TRY_TO_NUMBER(PLAYER_ID)                            AS PLAYER_ID,
    TRY_TO_DATE(DATE)                                   AS VALUATION_DATE,
    TRY_TO_NUMBER(MARKET_VALUE_IN_EUR)                  AS MARKET_VALUE_IN_EUR,
    TRY_TO_NUMBER(CURRENT_CLUB_ID)                      AS CURRENT_CLUB_ID,
    NULLIF(TRIM(PLAYER_CLUB_DOMESTIC_COMPETITION_ID), '') AS PLAYER_CLUB_DOMESTIC_COMPETITION_ID,
    _SOURCE_FILE                                        AS _SOURCE_FILE,
    _LOADED_AT                                          AS _RAW_LOADED_AT
  FROM FOOTBALL.SILVER.STREAM_RAW_PLAYER_VALUATIONS
  WHERE PLAYER_ID IS NOT NULL AND TRY_TO_DATE(DATE) IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY PLAYER_ID, TRY_TO_DATE(DATE)
    ORDER BY _LOADED_AT DESC
  ) = 1
) AS src
ON tgt.PLAYER_ID = src.PLAYER_ID AND tgt.VALUATION_DATE = src.VALUATION_DATE
WHEN MATCHED THEN UPDATE SET
  tgt.MARKET_VALUE_IN_EUR                 = src.MARKET_VALUE_IN_EUR,
  tgt.CURRENT_CLUB_ID                     = src.CURRENT_CLUB_ID,
  tgt.PLAYER_CLUB_DOMESTIC_COMPETITION_ID = src.PLAYER_CLUB_DOMESTIC_COMPETITION_ID,
  tgt._SOURCE_FILE                        = src._SOURCE_FILE,
  tgt._RAW_LOADED_AT                      = src._RAW_LOADED_AT,
  tgt._SILVER_LOADED_AT                   = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  PLAYER_ID, VALUATION_DATE, MARKET_VALUE_IN_EUR, CURRENT_CLUB_ID,
  PLAYER_CLUB_DOMESTIC_COMPETITION_ID,
  _SOURCE_FILE, _RAW_LOADED_AT, _SILVER_LOADED_AT
) VALUES (
  src.PLAYER_ID, src.VALUATION_DATE, src.MARKET_VALUE_IN_EUR,
  src.CURRENT_CLUB_ID, src.PLAYER_CLUB_DOMESTIC_COMPETITION_ID,
  src._SOURCE_FILE, src._RAW_LOADED_AT, CURRENT_TIMESTAMP()
);

ALTER TASK FOOTBALL.SILVER.TASK_LOAD_PLAYER_VALUATIONS RESUME;

-- Validación:
-- SELECT * FROM FOOTBALL.SILVER.PLAYER_VALUATIONS;
-- EXECUTE TASK FOOTBALL.SILVER.TASK_LOAD_PLAYER_VALUATIONS;
