-- =====================================================================
-- SILVER · 08_transfers.sql
-- FOOTBALL.RAW.TRANSFERS -> FOOTBALL.SILVER.TRANSFERS
--
-- AVISO (inferido, no verificado con datos reales): comprueba antes con
--   SELECT * FROM FOOTBALL.RAW.TRANSFERS LIMIT 5;
-- Esta tabla tampoco trae un id propio. Uso como clave de negocio
-- (PLAYER_ID, TRANSFER_DATE, TO_CLUB_ID) -- un jugador no debería tener
-- dos fichajes distintos el mismo día hacia el mismo club. Si al
-- ejecutar ves que esa combinación no es única en tus datos reales,
-- avísame y ajustamos la clave (por ejemplo añadiendo FROM_CLUB_ID).
-- =====================================================================

CREATE TABLE IF NOT EXISTS FOOTBALL.SILVER.TRANSFERS (
  PLAYER_ID               NUMBER    NOT NULL,
  TRANSFER_DATE            DATE      NOT NULL,
  TRANSFER_SEASON          STRING,
  FROM_CLUB_ID             NUMBER,
  TO_CLUB_ID               NUMBER    NOT NULL,
  FROM_CLUB_NAME           STRING,
  TO_CLUB_NAME             STRING,
  TRANSFER_FEE             NUMBER,
  MARKET_VALUE_IN_EUR      NUMBER,
  PLAYER_NAME              STRING,
  _SOURCE_FILE             STRING,
  _RAW_LOADED_AT           TIMESTAMP_NTZ,
  _SILVER_LOADED_AT        TIMESTAMP_NTZ,
  PRIMARY KEY (PLAYER_ID, TRANSFER_DATE, TO_CLUB_ID)
);

CREATE STREAM IF NOT EXISTS FOOTBALL.SILVER.STREAM_RAW_TRANSFERS
  ON TABLE FOOTBALL.RAW.TRANSFERS
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK FOOTBALL.SILVER.TASK_LOAD_TRANSFERS
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 30 8 * * 6 Europe/Madrid'
WHEN
  SYSTEM$STREAM_HAS_DATA('FOOTBALL.SILVER.STREAM_RAW_TRANSFERS')
AS
MERGE INTO FOOTBALL.SILVER.TRANSFERS AS tgt
USING (
  SELECT
    TRY_TO_NUMBER(PLAYER_ID)              AS PLAYER_ID,
    TRY_TO_DATE(TRANSFER_DATE)            AS TRANSFER_DATE,
    NULLIF(TRIM(TRANSFER_SEASON), '')     AS TRANSFER_SEASON,
    TRY_TO_NUMBER(FROM_CLUB_ID)           AS FROM_CLUB_ID,
    TRY_TO_NUMBER(TO_CLUB_ID)             AS TO_CLUB_ID,
    NULLIF(TRIM(FROM_CLUB_NAME), '')      AS FROM_CLUB_NAME,
    NULLIF(TRIM(TO_CLUB_NAME), '')        AS TO_CLUB_NAME,
    TRY_TO_NUMBER(TRANSFER_FEE)           AS TRANSFER_FEE,
    TRY_TO_NUMBER(MARKET_VALUE_IN_EUR)    AS MARKET_VALUE_IN_EUR,
    NULLIF(TRIM(PLAYER_NAME), '')         AS PLAYER_NAME,
    _SOURCE_FILE                          AS _SOURCE_FILE,
    _LOADED_AT                            AS _RAW_LOADED_AT
  FROM FOOTBALL.SILVER.STREAM_RAW_TRANSFERS
  WHERE PLAYER_ID IS NOT NULL
    AND TRY_TO_DATE(TRANSFER_DATE) IS NOT NULL
    AND TO_CLUB_ID IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY PLAYER_ID, TRY_TO_DATE(TRANSFER_DATE), TO_CLUB_ID
    ORDER BY _LOADED_AT DESC
  ) = 1
) AS src
ON tgt.PLAYER_ID = src.PLAYER_ID
   AND tgt.TRANSFER_DATE = src.TRANSFER_DATE
   AND tgt.TO_CLUB_ID = src.TO_CLUB_ID
WHEN MATCHED THEN UPDATE SET
  tgt.TRANSFER_SEASON     = src.TRANSFER_SEASON,
  tgt.FROM_CLUB_ID        = src.FROM_CLUB_ID,
  tgt.FROM_CLUB_NAME      = src.FROM_CLUB_NAME,
  tgt.TO_CLUB_NAME        = src.TO_CLUB_NAME,
  tgt.TRANSFER_FEE        = src.TRANSFER_FEE,
  tgt.MARKET_VALUE_IN_EUR = src.MARKET_VALUE_IN_EUR,
  tgt.PLAYER_NAME         = src.PLAYER_NAME,
  tgt._SOURCE_FILE        = src._SOURCE_FILE,
  tgt._RAW_LOADED_AT      = src._RAW_LOADED_AT,
  tgt._SILVER_LOADED_AT   = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  PLAYER_ID, TRANSFER_DATE, TRANSFER_SEASON, FROM_CLUB_ID, TO_CLUB_ID,
  FROM_CLUB_NAME, TO_CLUB_NAME, TRANSFER_FEE, MARKET_VALUE_IN_EUR,
  PLAYER_NAME, _SOURCE_FILE, _RAW_LOADED_AT, _SILVER_LOADED_AT
) VALUES (
  src.PLAYER_ID, src.TRANSFER_DATE, src.TRANSFER_SEASON,
  src.FROM_CLUB_ID, src.TO_CLUB_ID, src.FROM_CLUB_NAME, src.TO_CLUB_NAME,
  src.TRANSFER_FEE, src.MARKET_VALUE_IN_EUR, src.PLAYER_NAME,
  src._SOURCE_FILE, src._RAW_LOADED_AT, CURRENT_TIMESTAMP()
);

ALTER TASK FOOTBALL.SILVER.TASK_LOAD_TRANSFERS RESUME;

-- Validación:
-- SELECT * FROM FOOTBALL.SILVER.TRANSFERS;
-- EXECUTE TASK FOOTBALL.SILVER.TASK_LOAD_TRANSFERS;
