-- =====================================================================
-- SILVER · 09_countries.sql
-- FOOTBALL.RAW.COUNTRIES -> FOOTBALL.SILVER.COUNTRIES
--
-- AVISO (inferido, no verificado con datos reales): comprueba antes con
--   SELECT * FROM FOOTBALL.RAW.COUNTRIES LIMIT 5;
-- Es la tabla más pequeña y sencilla, buena candidata para verificar
-- rápido el patrón entero de punta a punta.
-- =====================================================================

CREATE TABLE IF NOT EXISTS FOOTBALL.SILVER.COUNTRIES (
  COUNTRY_ID          NUMBER        NOT NULL,
  COUNTRY_NAME        STRING,
  COUNTRY_LATITUDE    FLOAT,
  COUNTRY_LONGITUDE   FLOAT,
  _SOURCE_FILE        STRING,
  _RAW_LOADED_AT       TIMESTAMP_NTZ,
  _SILVER_LOADED_AT    TIMESTAMP_NTZ,
  PRIMARY KEY (COUNTRY_ID)
);

CREATE STREAM IF NOT EXISTS FOOTBALL.SILVER.STREAM_RAW_COUNTRIES
  ON TABLE FOOTBALL.RAW.COUNTRIES
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK FOOTBALL.SILVER.TASK_LOAD_COUNTRIES
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 30 8 * * 6 Europe/Madrid'
WHEN
  SYSTEM$STREAM_HAS_DATA('FOOTBALL.SILVER.STREAM_RAW_COUNTRIES')
AS
MERGE INTO FOOTBALL.SILVER.COUNTRIES AS tgt
USING (
  SELECT
    TRY_TO_NUMBER(COUNTRY_ID)          AS COUNTRY_ID,
    NULLIF(TRIM(COUNTRY_NAME), '')     AS COUNTRY_NAME,
    TRY_TO_DOUBLE(COUNTRY_LATITUDE)    AS COUNTRY_LATITUDE,
    TRY_TO_DOUBLE(COUNTRY_LONGITUDE)   AS COUNTRY_LONGITUDE,
    _SOURCE_FILE                       AS _SOURCE_FILE,
    _LOADED_AT                         AS _RAW_LOADED_AT
  FROM FOOTBALL.SILVER.STREAM_RAW_COUNTRIES
  WHERE COUNTRY_ID IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY COUNTRY_ID
    ORDER BY _LOADED_AT DESC
  ) = 1
) AS src
ON tgt.COUNTRY_ID = src.COUNTRY_ID
WHEN MATCHED THEN UPDATE SET
  tgt.COUNTRY_NAME       = src.COUNTRY_NAME,
  tgt.COUNTRY_LATITUDE   = src.COUNTRY_LATITUDE,
  tgt.COUNTRY_LONGITUDE  = src.COUNTRY_LONGITUDE,
  tgt._SOURCE_FILE       = src._SOURCE_FILE,
  tgt._RAW_LOADED_AT     = src._RAW_LOADED_AT,
  tgt._SILVER_LOADED_AT  = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  COUNTRY_ID, COUNTRY_NAME, COUNTRY_LATITUDE, COUNTRY_LONGITUDE,
  _SOURCE_FILE, _RAW_LOADED_AT, _SILVER_LOADED_AT
) VALUES (
  src.COUNTRY_ID, src.COUNTRY_NAME, src.COUNTRY_LATITUDE,
  src.COUNTRY_LONGITUDE, src._SOURCE_FILE, src._RAW_LOADED_AT,
  CURRENT_TIMESTAMP()
);

ALTER TASK FOOTBALL.SILVER.TASK_LOAD_COUNTRIES RESUME;

-- Validación:
-- SELECT * FROM FOOTBALL.SILVER.COUNTRIES;
-- EXECUTE TASK FOOTBALL.SILVER.TASK_LOAD_COUNTRIES;
