-- =====================================================================
-- GOLD · 02_dim_country.sql
-- FOOTBALL.SILVER.COUNTRIES -> FOOTBALL.GOLD.DIM_COUNTRY
--
-- IMPORTANTE: sustituye <TU_WAREHOUSE> por el nombre real de tu
-- warehouse antes de ejecutar el CREATE TASK.
--
-- ALCANCE (decisión explícita): esta dimensión se usa ÚNICAMENTE para
-- la nacionalidad del jugador (DIM_PLAYER.COUNTRY_OF_CITIZENSHIP ->
-- DIM_COUNTRY.COUNTRY_NAME). El país del club se queda como columna de
-- texto plano en DIM_CLUB, sin relación propia contra esta tabla --
-- evita a propósito el problema de "dimensión de rol" (ver README).
--
-- CLAVE: COUNTRY_NAME (texto), no COUNTRY_ID. SILVER.PLAYERS no trae un
-- id numérico de nacionalidad, solo el nombre del país -- así que
-- COUNTRY_ID aquí queda como referencia informativa, no como la clave
-- de la relación real en Power BI.
-- =====================================================================

-- CREATE OR REPLACE, no IF NOT EXISTS: fuerza el esquema aquí definido aunque ya exista una DIM_COUNTRY previa con columnas distintas.
CREATE OR REPLACE TABLE FOOTBALL.GOLD.DIM_COUNTRY (
  COUNTRY_NAME        STRING    NOT NULL,
  COUNTRY_ID          NUMBER,
  COUNTRY_LATITUDE    FLOAT,
  COUNTRY_LONGITUDE   FLOAT,
  PRIMARY KEY (COUNTRY_NAME)
);

-- Siembra inicial:
INSERT INTO FOOTBALL.GOLD.DIM_COUNTRY (COUNTRY_NAME, COUNTRY_ID, COUNTRY_LATITUDE, COUNTRY_LONGITUDE)
SELECT
  COUNTRY_NAME,
  MAX(COUNTRY_ID),
  MAX(COUNTRY_LATITUDE),
  MAX(COUNTRY_LONGITUDE)
FROM FOOTBALL.SILVER.COUNTRIES
WHERE COUNTRY_NAME IS NOT NULL
GROUP BY COUNTRY_NAME;

CREATE STREAM IF NOT EXISTS FOOTBALL.GOLD.STREAM_SILVER_COUNTRIES
  ON TABLE FOOTBALL.SILVER.COUNTRIES
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK FOOTBALL.GOLD.TASK_LOAD_DIM_COUNTRY
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 9 * * 6 Europe/Madrid'
WHEN
  SYSTEM$STREAM_HAS_DATA('FOOTBALL.GOLD.STREAM_SILVER_COUNTRIES')
AS
MERGE INTO FOOTBALL.GOLD.DIM_COUNTRY AS tgt
USING (
  SELECT
    COUNTRY_NAME,
    MAX(COUNTRY_ID)        AS COUNTRY_ID,
    MAX(COUNTRY_LATITUDE)  AS COUNTRY_LATITUDE,
    MAX(COUNTRY_LONGITUDE) AS COUNTRY_LONGITUDE
  FROM FOOTBALL.GOLD.STREAM_SILVER_COUNTRIES
  WHERE COUNTRY_NAME IS NOT NULL
  GROUP BY COUNTRY_NAME
) AS src
ON tgt.COUNTRY_NAME = src.COUNTRY_NAME
WHEN MATCHED THEN UPDATE SET
  tgt.COUNTRY_ID        = src.COUNTRY_ID,
  tgt.COUNTRY_LATITUDE  = src.COUNTRY_LATITUDE,
  tgt.COUNTRY_LONGITUDE = src.COUNTRY_LONGITUDE
WHEN NOT MATCHED THEN INSERT (COUNTRY_NAME, COUNTRY_ID, COUNTRY_LATITUDE, COUNTRY_LONGITUDE)
VALUES (src.COUNTRY_NAME, src.COUNTRY_ID, src.COUNTRY_LATITUDE, src.COUNTRY_LONGITUDE);

ALTER TASK FOOTBALL.GOLD.TASK_LOAD_DIM_COUNTRY RESUME;

-- Validación (esperado: 0 filas, o una lista corta y revisable):
-- SELECT DISTINCT p.COUNTRY_OF_CITIZENSHIP
-- FROM FOOTBALL.SILVER.PLAYERS p
-- LEFT JOIN FOOTBALL.GOLD.DIM_COUNTRY c ON p.COUNTRY_OF_CITIZENSHIP = c.COUNTRY_NAME
-- WHERE p.COUNTRY_OF_CITIZENSHIP IS NOT NULL AND c.COUNTRY_NAME IS NULL;
