-- =====================================================================
-- GOLD · 04_dim_club.sql
-- FOOTBALL.SILVER.CLUBS -> FOOTBALL.GOLD.DIM_CLUB
--
-- IMPORTANTE: sustituye <TU_WAREHOUSE> por el nombre real de tu
-- warehouse antes de ejecutar el CREATE TASK.
--
-- Passthrough casi directo de SILVER -- toda la limpieza de tipos ya se
-- resolvió ahí.
--
-- AVISO (a verificar): se asume que DOMESTIC_COMPETITION_ID usa el
-- mismo formato de identificador que DIM_COMPETITION.COMPETITION_ID
-- (es el join que usará Power BI). Consulta de validación al final.
-- =====================================================================

-- CREATE OR REPLACE, no IF NOT EXISTS: fuerza el esquema aquí definido aunque ya exista una DIM_CLUB previa con columnas distintas.
CREATE OR REPLACE TABLE FOOTBALL.GOLD.DIM_CLUB (
  CLUB_ID                   NUMBER        NOT NULL,
  CLUB_CODE                 STRING,
  CLUB_NAME                 STRING,
  DOMESTIC_COMPETITION_ID   STRING,
  STADIUM_NAME              STRING,
  STADIUM_SEATS             NUMBER,
  SQUAD_SIZE                NUMBER,
  AVERAGE_AGE               NUMBER(10,2),
  FOREIGNERS_NUMBER         NUMBER,
  FOREIGNERS_PERCENTAGE     NUMBER(10,2),
  NATIONAL_TEAM_PLAYERS     NUMBER,
  COACH_NAME                STRING,
  LAST_SEASON               NUMBER,
  TOTAL_MARKET_VALUE        NUMBER,
  NET_TRANSFER_RECORD       STRING,
  URL                       STRING,
  PRIMARY KEY (CLUB_ID)
);

-- Siembra inicial:
INSERT INTO FOOTBALL.GOLD.DIM_CLUB (
  CLUB_ID, CLUB_CODE, CLUB_NAME, DOMESTIC_COMPETITION_ID, STADIUM_NAME, STADIUM_SEATS,
  SQUAD_SIZE, AVERAGE_AGE, FOREIGNERS_NUMBER, FOREIGNERS_PERCENTAGE,
  NATIONAL_TEAM_PLAYERS, COACH_NAME, LAST_SEASON, TOTAL_MARKET_VALUE,
  NET_TRANSFER_RECORD, URL
)
SELECT
  CLUB_ID, CLUB_CODE, NAME AS CLUB_NAME, DOMESTIC_COMPETITION_ID, STADIUM_NAME, STADIUM_SEATS,
  SQUAD_SIZE, AVERAGE_AGE, FOREIGNERS_NUMBER, FOREIGNERS_PERCENTAGE,
  NATIONAL_TEAM_PLAYERS, COACH_NAME, LAST_SEASON, TOTAL_MARKET_VALUE,
  NET_TRANSFER_RECORD, URL
FROM FOOTBALL.SILVER.CLUBS;

CREATE STREAM IF NOT EXISTS FOOTBALL.GOLD.STREAM_SILVER_CLUBS
  ON TABLE FOOTBALL.SILVER.CLUBS
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK FOOTBALL.GOLD.TASK_LOAD_DIM_CLUB
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 9 * * 6 Europe/Madrid'
WHEN
  SYSTEM$STREAM_HAS_DATA('FOOTBALL.GOLD.STREAM_SILVER_CLUBS')
AS
MERGE INTO FOOTBALL.GOLD.DIM_CLUB AS tgt
USING (
  SELECT
    CLUB_ID, CLUB_CODE, NAME AS CLUB_NAME, DOMESTIC_COMPETITION_ID, STADIUM_NAME, STADIUM_SEATS,
    SQUAD_SIZE, AVERAGE_AGE, FOREIGNERS_NUMBER, FOREIGNERS_PERCENTAGE,
    NATIONAL_TEAM_PLAYERS, COACH_NAME, LAST_SEASON, TOTAL_MARKET_VALUE,
    NET_TRANSFER_RECORD, URL
  FROM FOOTBALL.GOLD.STREAM_SILVER_CLUBS
  WHERE CLUB_ID IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CLUB_ID
    ORDER BY _SILVER_LOADED_AT DESC
  ) = 1
) AS src
ON tgt.CLUB_ID = src.CLUB_ID
WHEN MATCHED THEN UPDATE SET
  tgt.CLUB_CODE               = src.CLUB_CODE,
  tgt.CLUB_NAME               = src.CLUB_NAME,
  tgt.DOMESTIC_COMPETITION_ID = src.DOMESTIC_COMPETITION_ID,
  tgt.STADIUM_NAME             = src.STADIUM_NAME,
  tgt.STADIUM_SEATS            = src.STADIUM_SEATS,
  tgt.SQUAD_SIZE                = src.SQUAD_SIZE,
  tgt.AVERAGE_AGE               = src.AVERAGE_AGE,
  tgt.FOREIGNERS_NUMBER         = src.FOREIGNERS_NUMBER,
  tgt.FOREIGNERS_PERCENTAGE     = src.FOREIGNERS_PERCENTAGE,
  tgt.NATIONAL_TEAM_PLAYERS     = src.NATIONAL_TEAM_PLAYERS,
  tgt.COACH_NAME                = src.COACH_NAME,
  tgt.LAST_SEASON               = src.LAST_SEASON,
  tgt.TOTAL_MARKET_VALUE        = src.TOTAL_MARKET_VALUE,
  tgt.NET_TRANSFER_RECORD       = src.NET_TRANSFER_RECORD,
  tgt.URL                       = src.URL
WHEN NOT MATCHED THEN INSERT (
  CLUB_ID, CLUB_CODE, CLUB_NAME, DOMESTIC_COMPETITION_ID, STADIUM_NAME, STADIUM_SEATS,
  SQUAD_SIZE, AVERAGE_AGE, FOREIGNERS_NUMBER, FOREIGNERS_PERCENTAGE,
  NATIONAL_TEAM_PLAYERS, COACH_NAME, LAST_SEASON, TOTAL_MARKET_VALUE,
  NET_TRANSFER_RECORD, URL
) VALUES (
  src.CLUB_ID, src.CLUB_CODE, src.CLUB_NAME, src.DOMESTIC_COMPETITION_ID, src.STADIUM_NAME,
  src.STADIUM_SEATS, src.SQUAD_SIZE, src.AVERAGE_AGE, src.FOREIGNERS_NUMBER,
  src.FOREIGNERS_PERCENTAGE, src.NATIONAL_TEAM_PLAYERS, src.COACH_NAME,
  src.LAST_SEASON, src.TOTAL_MARKET_VALUE, src.NET_TRANSFER_RECORD, src.URL
);

ALTER TASK FOOTBALL.GOLD.TASK_LOAD_DIM_CLUB RESUME;

-- Validación (esperado: 0 filas, o una lista corta y revisable):
-- SELECT DISTINCT cl.DOMESTIC_COMPETITION_ID
-- FROM FOOTBALL.GOLD.DIM_CLUB cl
-- LEFT JOIN FOOTBALL.GOLD.DIM_COMPETITION co ON cl.DOMESTIC_COMPETITION_ID = co.COMPETITION_ID
-- WHERE cl.DOMESTIC_COMPETITION_ID IS NOT NULL AND co.COMPETITION_ID IS NULL;
