-- =====================================================================
-- GOLD · 07_fact_club_game.sql
-- FOOTBALL.SILVER.CLUB_GAMES + FOOTBALL.SILVER.GAMES -> FOOTBALL.GOLD.FACT_CLUB_GAME
--
-- IMPORTANTE: sustituye <TU_WAREHOUSE> por el nombre real de tu
-- warehouse antes de ejecutar el CREATE TASK.
--
-- Tabla extra (no la pide el enunciado como mínimo). GRANO: club x
-- partido (una fila por cada uno de los dos clubes que disputan un
-- partido) -- ver justificación completa en el README de GOLD.
--
-- A diferencia de FACT_PLAYER_SEASON, esta sí es una copia 1 a 1 de
-- CLUB_GAMES (mismo grano origen y destino, GAME_ID+CLUB_ID en ambas),
-- así que el patrón STREAM+TASK es idéntico al que ya usa SILVER --
-- solo se le añade el JOIN a GAMES para traer SEASON/COMPETITION/fecha.
-- =====================================================================

-- CREATE OR REPLACE, no IF NOT EXISTS: fuerza el esquema aquí definido aunque ya exista una FACT_CLUB_GAME previa con columnas distintas.
CREATE OR REPLACE TABLE FOOTBALL.GOLD.FACT_CLUB_GAME (
  GAME_ID          NUMBER    NOT NULL,
  CLUB_ID          NUMBER    NOT NULL,
  SEASON_ID        NUMBER,
  COMPETITION_ID   STRING,
  GAME_DATE        DATE,
  OPPONENT_ID      NUMBER,
  OWN_GOALS        NUMBER,
  OPPONENT_GOALS   NUMBER,
  HOSTING          STRING,
  IS_WIN           NUMBER,
  RESULT           STRING,
  PRIMARY KEY (GAME_ID, CLUB_ID)
);

-- Siembra inicial:
INSERT INTO FOOTBALL.GOLD.FACT_CLUB_GAME (
  GAME_ID, CLUB_ID, SEASON_ID, COMPETITION_ID, GAME_DATE, OPPONENT_ID,
  OWN_GOALS, OPPONENT_GOALS, HOSTING, IS_WIN, RESULT
)
SELECT
  cg.GAME_ID, cg.CLUB_ID, g.SEASON, g.COMPETITION_ID, g.GAME_DATE,
  cg.OPPONENT_ID, cg.OWN_GOALS, cg.OPPONENT_GOALS, cg.HOSTING, cg.IS_WIN,
  CASE
    WHEN cg.OWN_GOALS > cg.OPPONENT_GOALS THEN 'WIN'
    WHEN cg.OWN_GOALS = cg.OPPONENT_GOALS THEN 'DRAW'
    WHEN cg.OWN_GOALS < cg.OPPONENT_GOALS THEN 'LOSS'
  END
FROM FOOTBALL.SILVER.CLUB_GAMES cg
JOIN FOOTBALL.SILVER.GAMES g ON cg.GAME_ID = g.GAME_ID;

CREATE STREAM IF NOT EXISTS FOOTBALL.GOLD.STREAM_SILVER_CLUB_GAMES
  ON TABLE FOOTBALL.SILVER.CLUB_GAMES
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK FOOTBALL.GOLD.TASK_LOAD_FACT_CLUB_GAME
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 9 * * 6 Europe/Madrid'
WHEN
  SYSTEM$STREAM_HAS_DATA('FOOTBALL.GOLD.STREAM_SILVER_CLUB_GAMES')
AS
MERGE INTO FOOTBALL.GOLD.FACT_CLUB_GAME AS tgt
USING (
  SELECT
    cg.GAME_ID, cg.CLUB_ID, g.SEASON AS SEASON_ID, g.COMPETITION_ID, g.GAME_DATE,
    cg.OPPONENT_ID, cg.OWN_GOALS, cg.OPPONENT_GOALS, cg.HOSTING, cg.IS_WIN,
    CASE
      WHEN cg.OWN_GOALS > cg.OPPONENT_GOALS THEN 'WIN'
      WHEN cg.OWN_GOALS = cg.OPPONENT_GOALS THEN 'DRAW'
      WHEN cg.OWN_GOALS < cg.OPPONENT_GOALS THEN 'LOSS'
    END AS RESULT
  FROM FOOTBALL.GOLD.STREAM_SILVER_CLUB_GAMES cg
  JOIN FOOTBALL.SILVER.GAMES g ON cg.GAME_ID = g.GAME_ID
  WHERE cg.GAME_ID IS NOT NULL AND cg.CLUB_ID IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY cg.GAME_ID, cg.CLUB_ID
    ORDER BY cg._SILVER_LOADED_AT DESC
  ) = 1
) AS src
ON tgt.GAME_ID = src.GAME_ID AND tgt.CLUB_ID = src.CLUB_ID
WHEN MATCHED THEN UPDATE SET
  tgt.SEASON_ID       = src.SEASON_ID,
  tgt.COMPETITION_ID  = src.COMPETITION_ID,
  tgt.GAME_DATE       = src.GAME_DATE,
  tgt.OPPONENT_ID     = src.OPPONENT_ID,
  tgt.OWN_GOALS       = src.OWN_GOALS,
  tgt.OPPONENT_GOALS  = src.OPPONENT_GOALS,
  tgt.HOSTING         = src.HOSTING,
  tgt.IS_WIN          = src.IS_WIN,
  tgt.RESULT          = src.RESULT
WHEN NOT MATCHED THEN INSERT (
  GAME_ID, CLUB_ID, SEASON_ID, COMPETITION_ID, GAME_DATE, OPPONENT_ID,
  OWN_GOALS, OPPONENT_GOALS, HOSTING, IS_WIN, RESULT
) VALUES (
  src.GAME_ID, src.CLUB_ID, src.SEASON_ID, src.COMPETITION_ID, src.GAME_DATE,
  src.OPPONENT_ID, src.OWN_GOALS, src.OPPONENT_GOALS, src.HOSTING, src.IS_WIN,
  src.RESULT
);

ALTER TASK FOOTBALL.GOLD.TASK_LOAD_FACT_CLUB_GAME RESUME;

-- Validación:
-- SELECT COUNT(*), COUNT(DISTINCT GAME_ID) FROM FOOTBALL.GOLD.FACT_CLUB_GAME;
