-- =====================================================================
-- GOLD · 08_fact_transfer.sql
-- FOOTBALL.SILVER.TRANSFERS -> FOOTBALL.GOLD.FACT_TRANSFER
--
-- IMPORTANTE: sustituye <TU_WAREHOUSE> por el nombre real de tu
-- warehouse antes de ejecutar el CREATE TASK.
--
-- Tabla extra (no la pide el enunciado como mínimo), conectada con la
-- pregunta de "oportunidades" (score alto / valor bajo). Passthrough
-- casi directo de SILVER.TRANSFERS -- mismo grano origen y destino, así
-- que el patrón STREAM+TASK es idéntico al de SILVER.
--
-- MARKET_VALUE_IN_EUR se renombra a MARKET_VALUE_AT_TRANSFER_EUR para
-- no confundirlo con el valor de mercado "de temporada" que ya aparece
-- en FACT_PLAYER_SEASON -- aquí es el valor en el momento exacto del
-- fichaje, no el de una temporada completa.
-- =====================================================================

-- CREATE OR REPLACE, no IF NOT EXISTS: fuerza el esquema aquí definido aunque ya exista una FACT_TRANSFER previa con columnas distintas.
CREATE OR REPLACE TABLE FOOTBALL.GOLD.FACT_TRANSFER (
  PLAYER_ID                       NUMBER    NOT NULL,
  TRANSFER_DATE                    DATE      NOT NULL,
  TRANSFER_SEASON                  STRING,
  FROM_CLUB_ID                     NUMBER,
  TO_CLUB_ID                       NUMBER    NOT NULL,
  TRANSFER_FEE                     NUMBER,
  MARKET_VALUE_AT_TRANSFER_EUR     NUMBER,
  PRIMARY KEY (PLAYER_ID, TRANSFER_DATE, TO_CLUB_ID)
);

-- Siembra inicial:
INSERT INTO FOOTBALL.GOLD.FACT_TRANSFER (
  PLAYER_ID, TRANSFER_DATE, TRANSFER_SEASON, FROM_CLUB_ID, TO_CLUB_ID,
  TRANSFER_FEE, MARKET_VALUE_AT_TRANSFER_EUR
)
SELECT
  PLAYER_ID, TRANSFER_DATE, TRANSFER_SEASON, FROM_CLUB_ID, TO_CLUB_ID,
  TRANSFER_FEE, MARKET_VALUE_IN_EUR
FROM FOOTBALL.SILVER.TRANSFERS;

CREATE STREAM IF NOT EXISTS FOOTBALL.GOLD.STREAM_SILVER_TRANSFERS
  ON TABLE FOOTBALL.SILVER.TRANSFERS
  APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK FOOTBALL.GOLD.TASK_LOAD_FACT_TRANSFER
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 9 * * 6 Europe/Madrid'
WHEN
  SYSTEM$STREAM_HAS_DATA('FOOTBALL.GOLD.STREAM_SILVER_TRANSFERS')
AS
MERGE INTO FOOTBALL.GOLD.FACT_TRANSFER AS tgt
USING (
  SELECT
    PLAYER_ID, TRANSFER_DATE, TRANSFER_SEASON, FROM_CLUB_ID, TO_CLUB_ID,
    TRANSFER_FEE, MARKET_VALUE_IN_EUR AS MARKET_VALUE_AT_TRANSFER_EUR
  FROM FOOTBALL.GOLD.STREAM_SILVER_TRANSFERS
  WHERE PLAYER_ID IS NOT NULL AND TRANSFER_DATE IS NOT NULL AND TO_CLUB_ID IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY PLAYER_ID, TRANSFER_DATE, TO_CLUB_ID
    ORDER BY _SILVER_LOADED_AT DESC
  ) = 1
) AS src
ON tgt.PLAYER_ID = src.PLAYER_ID
  AND tgt.TRANSFER_DATE = src.TRANSFER_DATE
  AND tgt.TO_CLUB_ID = src.TO_CLUB_ID
WHEN MATCHED THEN UPDATE SET
  tgt.TRANSFER_SEASON              = src.TRANSFER_SEASON,
  tgt.FROM_CLUB_ID                 = src.FROM_CLUB_ID,
  tgt.TRANSFER_FEE                 = src.TRANSFER_FEE,
  tgt.MARKET_VALUE_AT_TRANSFER_EUR = src.MARKET_VALUE_AT_TRANSFER_EUR
WHEN NOT MATCHED THEN INSERT (
  PLAYER_ID, TRANSFER_DATE, TRANSFER_SEASON, FROM_CLUB_ID, TO_CLUB_ID,
  TRANSFER_FEE, MARKET_VALUE_AT_TRANSFER_EUR
) VALUES (
  src.PLAYER_ID, src.TRANSFER_DATE, src.TRANSFER_SEASON, src.FROM_CLUB_ID,
  src.TO_CLUB_ID, src.TRANSFER_FEE, src.MARKET_VALUE_AT_TRANSFER_EUR
);

ALTER TASK FOOTBALL.GOLD.TASK_LOAD_FACT_TRANSFER RESUME;

-- Validación:
-- SELECT * FROM FOOTBALL.GOLD.FACT_TRANSFER;
